DROP TABLE IF EXISTS participation CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS fenetre_com CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS mission CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS affectation_station CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS station_sol CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS centre_controle CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS embarquement CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS instrument CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS historique_statut CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS satellite CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS orbite CASCADE CONSTRAINTS PURGE;

CREATE TABLE orbite (
    id_orbite NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    type_orbite VARCHAR2(10) NOT NULL,
    altitude NUMBER(5) NOT NULL,
    inclinaison NUMBER(5,2) NOT NULL,
    periode_orbitale NUMBER(6,2) NOT NULL,
    excentricite NUMBER(6,4) NOT NULL,
    zone_couverture VARCHAR2(200) NOT NULL,
    CONSTRAINT pk_orbite PRIMARY KEY (id_orbite),
    CONSTRAINT uq_orbite_altitude_inclinaison UNIQUE (altitude, inclinaison),
    CONSTRAINT chk_orbite_type CHECK (type_orbite IN ('LEO', 'MEO', 'SSO', 'GEO'))
);

CREATE TABLE satellite (
    id_satellite VARCHAR2(20) NOT NULL,
    nom_satellite VARCHAR2(100) NOT NULL,
    date_lancement DATE NOT NULL,
    masse NUMBER(5,2) NOT NULL,
    format_cubesat VARCHAR2(5) NOT NULL,
    statut VARCHAR2(30) NOT NULL,
    duree_vie_prevue NUMBER(4) NOT NULL,
    capacite_batterie NUMBER(6,1) NOT NULL,
    id_orbite NUMBER NOT NULL,
    CONSTRAINT pk_satellite PRIMARY KEY (id_satellite),
    CONSTRAINT fk_satellite_orbite FOREIGN KEY (id_orbite) REFERENCES orbite (id_orbite),
    CONSTRAINT chk_satellite_format CHECK (format_cubesat IN ('1U', '3U', '6U', '12U')),
    CONSTRAINT chk_satellite_statut CHECK (statut IN ('Opérationnel', 'En veille', 'Défaillant', 'Désorbité'))
);

CREATE TABLE historique_statut (
    id_historique NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) NOT NULL,
    id_satellite VARCHAR2(20) NOT NULL,
    ancien_statut VARCHAR2(30) NOT NULL,
    nouveau_statut VARCHAR2(30) NOT NULL,
    date_changement TIMESTAMP NOT NULL,
    motif VARCHAR2(500) DEFAULT 'Changement de statut' NOT NULL,
    CONSTRAINT pk_historique_statut PRIMARY KEY (id_historique),
    CONSTRAINT fk_hist_satellite FOREIGN KEY (id_satellite) REFERENCES satellite (id_satellite),
    CONSTRAINT chk_hist_ancien_statut CHECK (ancien_statut IN ('Opérationnel', 'En veille', 'Défaillant', 'Désorbité')),
    CONSTRAINT chk_hist_nouveau_statut CHECK (nouveau_statut IN ('Opérationnel', 'En veille', 'Défaillant', 'Désorbité'))
);

CREATE TABLE instrument (
    ref_instrument VARCHAR2(20) NOT NULL,
    type_instrument VARCHAR2(50) NOT NULL,
    modele VARCHAR2(100) NOT NULL,
    resolution NUMBER(6,1),
    consommation NUMBER(5,2) NOT NULL,
    masse NUMBER(5,3) NOT NULL,
    CONSTRAINT pk_instrument PRIMARY KEY (ref_instrument)
);

CREATE TABLE embarquement (
    id_satellite VARCHAR2(20) NOT NULL,
    ref_instrument VARCHAR2(20) NOT NULL,
    date_integration DATE NOT NULL,
    etat_fonctionnement VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_embarquement PRIMARY KEY (id_satellite, ref_instrument),
    CONSTRAINT fk_emb_satellite FOREIGN KEY (id_satellite) REFERENCES satellite (id_satellite),
    CONSTRAINT fk_emb_instrument FOREIGN KEY (ref_instrument) REFERENCES instrument (ref_instrument),
    CONSTRAINT chk_emb_etat CHECK (etat_fonctionnement IN ('Nominal', 'Dégradé', 'Hors service'))
);

CREATE TABLE centre_controle (
    id_centre NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    nom_centre VARCHAR2(100) NOT NULL,
    ville VARCHAR2(50) NOT NULL,
    region_geo VARCHAR2(50) NOT NULL,
    fuseau_horaire VARCHAR2(50) NOT NULL,
    statut VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_centre_controle PRIMARY KEY (id_centre),
    CONSTRAINT chk_centre_statut CHECK (statut IN ('Actif', 'Inactif'))
);

CREATE TABLE station_sol (
    code_station VARCHAR2(20) NOT NULL,
    nom_station VARCHAR2(100) NOT NULL,
    latitude NUMBER(9,6) NOT NULL,
    longitude NUMBER(9,6) NOT NULL,
    diametre_antenne NUMBER(4,1) NOT NULL,
    bande_frequence VARCHAR2(10) NOT NULL,
    debit_max NUMBER(6,1) NOT NULL,
    statut VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_station_sol PRIMARY KEY (code_station),
    CONSTRAINT chk_station_bande CHECK (bande_frequence IN ('UHF', 'S', 'X', 'Ka')),
    CONSTRAINT chk_station_statut CHECK (statut IN ('Active', 'Maintenance', 'Inactive'))
);

CREATE TABLE affectation_station (
    id_centre NUMBER NOT NULL,
    code_station VARCHAR2(20) NOT NULL,
    date_affectation DATE NOT NULL,
    CONSTRAINT pk_affectation_station PRIMARY KEY (id_centre, code_station),
    CONSTRAINT fk_aff_centre FOREIGN KEY (id_centre) REFERENCES centre_controle (id_centre),
    CONSTRAINT fk_aff_station FOREIGN KEY (code_station) REFERENCES station_sol (code_station),
    CONSTRAINT uq_affectation_station UNIQUE (code_station)
);

CREATE TABLE mission (
    id_mission VARCHAR2(20) NOT NULL,
    nom_mission VARCHAR2(100) NOT NULL,
    objectif VARCHAR2(500) NOT NULL,
    zone_geo_cible VARCHAR2(200) NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE,
    statut_mission VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_mission PRIMARY KEY (id_mission),
    CONSTRAINT chk_mission_statut CHECK (statut_mission IN ('Active', 'Terminée')),
    CONSTRAINT chk_mission_dates CHECK (date_fin IS NULL OR date_fin >= date_debut)
);

CREATE TABLE fenetre_com (
    id_fenetre NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) NOT NULL,
    datetime_debut TIMESTAMP NOT NULL,
    duree NUMBER(4) NOT NULL,
    elevation_max NUMBER(5,2) NOT NULL,
    volume_donnees NUMBER(8,1),
    statut VARCHAR2(20) NOT NULL,
    id_satellite VARCHAR2(20) NOT NULL,
    code_station VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_fenetre_com PRIMARY KEY (id_fenetre),
    CONSTRAINT fk_fenetre_satellite FOREIGN KEY (id_satellite) REFERENCES satellite (id_satellite),
    CONSTRAINT fk_fenetre_station FOREIGN KEY (code_station) REFERENCES station_sol (code_station),
    CONSTRAINT chk_fenetre_duree CHECK (duree BETWEEN 1 AND 900),
    CONSTRAINT chk_fenetre_statut CHECK (statut IN ('Planifiée', 'Réalisée', 'Annulée')),
    CONSTRAINT chk_fenetre_volume CHECK (volume_donnees IS NULL OR volume_donnees >= 0)
);

CREATE TABLE participation (
    id_satellite VARCHAR2(20) NOT NULL,
    id_mission VARCHAR2(20) NOT NULL,
    role_satellite VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_participation PRIMARY KEY (id_satellite, id_mission),
    CONSTRAINT fk_participation_satellite FOREIGN KEY (id_satellite) REFERENCES satellite (id_satellite),
    CONSTRAINT fk_participation_mission FOREIGN KEY (id_mission) REFERENCES mission (id_mission)
);

COMMENT ON TABLE orbite IS 'Referentiel des plans orbitaux NanoOrbit';
COMMENT ON TABLE satellite IS 'Flotte de CubeSats NanoOrbit';
COMMENT ON TABLE historique_statut IS 'Trace des changements de statut des satellites';
COMMENT ON TABLE instrument IS 'Catalogue des instruments embarquables';
COMMENT ON TABLE embarquement IS 'Association SATELLITE - INSTRUMENT avec attributs propres';
COMMENT ON TABLE centre_controle IS 'Centres d operation NanoOrbit';
COMMENT ON TABLE station_sol IS 'Stations au sol de communication';
COMMENT ON TABLE affectation_station IS 'Rattachement logique d une station a un centre';
COMMENT ON TABLE mission IS 'Missions scientifiques NanoOrbit';
COMMENT ON TABLE fenetre_com IS 'Fenetres de communication satellite-station';
COMMENT ON TABLE participation IS 'Association SATELLITE - MISSION avec role';
