services:
  oracle-db:
    image: gvenzl/oracle-free:23.7-slim-faststart
    container_name: NanoOrbit_oracle_23ai
    ports:
      - "1521:1521"
    environment:
      # Mot de passe pour SYS, SYSTEM et PDBADMIN
      - ORACLE_PASSWORD=Efrei_2026_NO
      # Optionnel : Créer un utilisateur spécifique dès le démarrage
      - APP_USER=NO_ADMIN
      - APP_USER_PASSWORD=Admin_NO_2026
    volumes:
      # Persistance des données (indispensable pour les TP)
      - nanoOrbit:/opt/oracle/oradata
      # Scripts SQL sources montés en lecture seule
      - ./scripts:/workspace/sql:ro
      # Bootstrap relancé à chaque démarrage de la base
      - ./bootstrap/00-run-bootstrap.sh:/container-entrypoint-startdb.d/00-run-bootstrap.sh:ro

volumes:
  nanoOrbit:
